name: flutter_task
description: "Flutter task"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3
  objectbox: ^4.0.1
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  build_runner: ^2.4.11
  objectbox_generator: any

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
