// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/db/entities/data_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4628848801787130501),
      name: 'DataEntity',
      lastPropertyId: const obx_int.IdUid(9, 9945396781129642),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7897658662797024),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3291951611031694831),
            name: 'date',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 297077961486332927),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 9148882687315135583),
            name: 'category',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1641538458135613664),
            name: 'location',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 102478777376964039),
            name: 'parsedDate',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8367106814090813248),
            name: 'parsedTime',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 9945396781129642),
            name: 'timeOfDay',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 4628848801787130501),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [701125089522261601],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    DataEntity: obx_int.EntityDefinition<DataEntity>(
        model: _entities[0],
        toOneRelations: (DataEntity object) => [],
        toManyRelations: (DataEntity object) => {},
        getId: (DataEntity object) => object.id,
        setId: (DataEntity object, int id) {
          object.id = id;
        },
        objectToFB: (DataEntity object, fb.Builder fbb) {
          final dateOffset = fbb.writeString(object.date);
          final nameOffset = fbb.writeString(object.name);
          final categoryOffset = fbb.writeString(object.category);
          final locationOffset = fbb.writeString(object.location);
          final parsedDateOffset = fbb.writeString(object.parsedDate);
          final parsedTimeOffset = fbb.writeString(object.parsedTime);
          final timeOfDayOffset = fbb.writeString(object.timeOfDay);
          fbb.startTable(10);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(2, dateOffset);
          fbb.addOffset(3, nameOffset);
          fbb.addOffset(4, categoryOffset);
          fbb.addOffset(5, locationOffset);
          fbb.addOffset(6, parsedDateOffset);
          fbb.addOffset(7, parsedTimeOffset);
          fbb.addOffset(8, timeOfDayOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          final dateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final categoryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final locationParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final parsedDateParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final parsedTimeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final timeOfDayParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 20, '');
          final object = DataEntity(
              id: idParam,
              date: dateParam,
              name: nameParam,
              category: categoryParam,
              location: locationParam,
              parsedDate: parsedDateParam,
              parsedTime: parsedTimeParam,
              timeOfDay: timeOfDayParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DataEntity] entity fields to define ObjectBox queries.
class DataEntity_ {
  /// See [DataEntity.id].
  static final id =
      obx.QueryIntegerProperty<DataEntity>(_entities[0].properties[0]);

  /// See [DataEntity.date].
  static final date =
      obx.QueryStringProperty<DataEntity>(_entities[0].properties[1]);

  /// See [DataEntity.name].
  static final name =
      obx.QueryStringProperty<DataEntity>(_entities[0].properties[2]);

  /// See [DataEntity.category].
  static final category =
      obx.QueryStringProperty<DataEntity>(_entities[0].properties[3]);

  /// See [DataEntity.location].
  static final location =
      obx.QueryStringProperty<DataEntity>(_entities[0].properties[4]);

  /// See [DataEntity.parsedDate].
  static final parsedDate =
      obx.QueryStringProperty<DataEntity>(_entities[0].properties[5]);

  /// See [DataEntity.parsedTime].
  static final parsedTime =
      obx.QueryStringProperty<DataEntity>(_entities[0].properties[6]);

  /// See [DataEntity.timeOfDay].
  static final timeOfDay =
      obx.QueryStringProperty<DataEntity>(_entities[0].properties[7]);
}
